apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-deploy
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: hotstar
  template:
    metadata:
      labels:
        app: hotstar
    spec:
      containers:
      - name: hotstar
        image: veeranarni/hotstar:latest
        ports:
        - containerPort: 3000
